import type { APIGatewayProxyHandler } from 'aws-lambda';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY!;
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`;

export const handler: APIGatewayProxyHandler = async (event) => {
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type,Authorization',
    'Content-Type': 'application/json',
  };

  if (event.httpMethod === 'OPTIONS') return { statusCode: 200, headers, body: '' };

  try {
    const body = JSON.parse(event.body || '{}');
    const { resumeBase64, resumeMimeType, company, domain, userName } = body;

    if (!resumeBase64 || !company) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'resumeBase64 and company are required' }),
      };
    }

    console.log(`Generating email for ${company}`);
    const prompt = `You are a senior recruiter and executive communication specialist who has helped thousands of candidates land roles at top companies.

    A job seeker wants to send a cold outreach email directly to the HR or talent acquisition team at ${company}${domain ? ` (${domain})` : ''}.

    Your job:
    1. Read the entire resume carefully — every project, skill, technology, achievement, and role
    2. Understand what ${company} does, what kind of talent they hire, and what would impress their recruiting team
    3. Write a professional, compelling cold outreach email that makes the recruiter want to respond

    EMAIL QUALITY STANDARDS:
    - This email must feel like it was written by a thoughtful professional, not generated by AI
    - It must reference specific things from the resume — project names, technologies used, measurable outcomes if present
    - It must show the candidate understands ${company}'s domain and can add value to it
    - The subject line must be specific enough that it could not have been sent to any other company
    - The opening must immediately communicate relevance — not background, not pleasantries
    - The body should flow naturally across 3-4 paragraphs, each with a clear purpose:
      Paragraph 1: Who you are and why ${company} specifically — one strong hook
      Paragraph 2: Your strongest relevant project or experience with specifics from the resume
      Paragraph 3: What you bring to ${company} — connect your skills to their likely needs
      Paragraph 4 (optional): Brief, confident CTA — a 15-minute call, a portfolio link, an introduction
    - The closing should be warm but professional
    - Sign off with the candidate's actual name from the resume

    TONE: Professional, confident, direct. Not desperate, not arrogant. Like a strong candidate who knows their value and respects the recruiter's time.

    STRICT OUTPUT FORMAT — follow exactly:
    SUBJECT: [your subject line here]
    BODY:
    [full email body here, with blank lines between paragraphs]`;

    const geminiPayload = {
      contents: [
        {
          parts: [
            {
              inline_data: {
                mime_type: resumeMimeType || 'application/pdf',
                data: resumeBase64,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.75,
        maxOutputTokens: 8192, // FIXED: was 1024, emails were getting cut off
      },
    };

    const res = await fetch(GEMINI_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(geminiPayload),
      signal: AbortSignal.timeout(25000),
    });

    if (!res.ok) {
      const err = await res.json();
      console.error('Gemini error:', err);
      throw new Error(err.error?.message || 'Gemini API failed');
    }

    const geminiData = await res.json();
    const rawText: string = geminiData.candidates?.[0]?.content?.parts?.[0]?.text || '';

    console.log('Gemini raw output:', rawText);

    if (!rawText) throw new Error('Empty response from Gemini');

    // ── Parse the plain text response ────────────────────────────────────────
    let subject = '';
    let emailBody = '';

    // Strategy 1: Parse "SUBJECT: ...\nBODY: ..." format
    const subjectMatch = rawText.match(/^SUBJECT:\s*(.+)$/m);
    const bodyMatch = rawText.match(/^BODY:\s*([\s\S]+)$/m);

    if (subjectMatch && bodyMatch) {
      subject = subjectMatch[1].trim();
      emailBody = bodyMatch[1].trim();
    } else {
      // Strategy 2: Gemini returned JSON despite instructions — parse it out
      try {
        const cleaned = rawText.replace(/```json|```/g, '').trim();
        
        // Handle double-encoded JSON (JSON inside a JSON string)
        let parsed = JSON.parse(cleaned);
        
        // If body itself is a JSON string, parse it again
        if (typeof parsed.body === 'string' && parsed.body.trim().startsWith('{')) {
          try {
            const innerParsed = JSON.parse(parsed.body);
            subject = innerParsed.subject || parsed.subject || '';
            emailBody = innerParsed.body || '';
          } catch {
            subject = parsed.subject || '';
            emailBody = parsed.body || '';
          }
        } else {
          subject = parsed.subject || '';
          emailBody = parsed.body || '';
        }

        // Unescape \n sequences if they exist as literal strings
        emailBody = emailBody.replace(/\\n/g, '\n');
        subject = subject.replace(/\\n/g, '').trim();

      } catch {
        // Strategy 3: Just use the raw text and extract what we can
        const lines = rawText.split('\n').filter((l: string) => l.trim());
        subject = lines[0]?.replace(/^(subject:|re:|from:)/i, '').trim() || `Opportunity at ${company}`;
        emailBody = lines.slice(1).join('\n').trim() || rawText;
      }
    }

    // Final cleanup
    subject = subject.replace(/^["']|["']$/g, '').trim(); // strip surrounding quotes
    emailBody = emailBody.replace(/^["']|["']$/g, '').trim();

    // Sanity check — if body still looks like JSON, something went wrong
    if (emailBody.startsWith('{') || emailBody.startsWith('"subject"')) {
      throw new Error('Gemini returned malformed response — retry');
    }

    console.log(`Parsed subject: ${subject}`);
    console.log(`Parsed body length: ${emailBody.length} chars`);

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ subject, body: emailBody }),
    };

  } catch (err: any) {
    console.error('Generate email error:', err);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: err.message }),
    };
  }
};